"""Initial

Revision ID: 831258bcef0a
Revises: 
Create Date: 2021-02-04 09:02:18.536768

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '831258bcef0a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('entry_type', sa.String(), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('wee', sa.Boolean(), nullable=True),
    sa.Column('poo', sa.Boolean(), nullable=True),
    sa.Column('full', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_entries_created_at'), 'entries', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_entries_created_at'), table_name='entries')
    op.drop_table('entries')
    # ### end Alembic commands ###
