version: '3'

services:
  webapp:
    image: ${WEBAPP_IMAGE}
    container_name: babylogger_webapp
    expose:
      - 5000
    depends_on:
      - db
      - fastapi

  fastapi:
    container_name: babylogger_fastapi
    image: ${API_IMAGE}
    expose:
      - 8000
    environment:
      POSTGRES_PASS: ${POSTGRES_PASS}
    depends_on:
      - db
      
  db:
    container_name: babylogger_postgres
    restart: on-failure
    image: postgres
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASS}
      POSTGRES_DB: ${POSTGRES_DATABASE}
    volumes:
      - ./backend/db_data:/var/lib/postgresql/data

  caddy:
    image: caddy:2-alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - ./caddy/data:/data
      - ./caddy/config:/config

volumes:
  db_data: {}