version: '3'

services:
  webapp:
    container_name: babylogger_webapp
    build:
      context: ./vue-app
      dockerfile: Dockerfile
    expose:
      - 5000
    volumes:
      - './vue-app/:/vue-app/'
      - /vue-app/node_modules/
    depends_on:
      - db
      - fastapi

  fastapi:
    container_name: babylogger_fastapi
    expose:
      - 8000
    environment:
      POSTGRES_PASS: supersecurepass
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - './backend/:/backend/'
      - /backend/BabyLoggerAPIEnv/
    depends_on:
      - db

  db:
    container_name: babylogger_postgres
    restart: on-failure
    image: postgres
    environment:
      POSTGRES_PASSWORD: supersecurepass
      POSTGRES_DB: babylogger
    volumes:
      - ./backend/db_data:/var/lib/postgresql/data

  caddy:
    image: caddy:2-alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./caddy/Caddyfile.dev:/etc/caddy/Caddyfile